version: "3.2"
services:

######### FRONTENDS ##########
     
#Portainer - WebUI for Containers
  portainer:
    image: portainer/portainer
    container_name: portainer
    hostname: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/portainer/data:/data
      - /volume1/docker/shared:/shared
    environment:
      - TZ="America/New_York"
  
# Heimdall - Unified HTPC/Home Server Web Interface
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    hostname: heimdall
    restart: always
    volumes:
      - /volume1/docker/heimdall:/config
      - /volume1/docker/shared:/shared
    ports:
      - 446:443
      - 82:80
    environment:
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"

# phpMyAdmin - WebUI for MariaDB
  phpmyadmin:
    image: phpmyadmin/phpmyadmin  
    container_name: phpmyadmin
    hostname: phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - 84:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=password

# netdata - Lots of cool graphs
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: netdata
    hostname: 192.168.1.208
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro  

# calibre-web - webinterface for calibre library
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    hostname: calibre-web
    restart: always
    ports:
      - 8084:8083
    environment:
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"
    volumes:
      - /volume1/docker/calibre-web:/config
      - /volume1/Media/Books/Calibre:/books
      - /volume1/docker/shared:/shared     

######### DOCKER RELATED ##########

# Watchtower - Automatic Update of Containers/Apps
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    hostname: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup

######### SMART HOME APPS ##########

# Home Assistant - Smart Home Hub
  homeassistant:
    image: homeassistant/home-assistant  
    container_name: homeassistant
    hostname: homeassistant
    restart: always
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /volume1/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/shared:/shared
    ports:
      - 8123:8123
    privileged: true
    environment:
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"

######### DOWNLOADERS ##########

# Transmission with VPN – Bittorrent Downloader
  transmission-vpn-radarr:
    image: haugene/transmission-openvpn
    container_name: transmission-vpn-radarr
    hostname: transmission-vpn-radarr
    restart: always    
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 9091:9091
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /volume1/docker/transmission-vpn-radarr:/data
      - /volume1/docker/shared:/shared
      - /volume1/Downloads:/data/watch
      - /volume1/Downloads/completed:/data/completed
      - /volume1/Downloads/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=username
      - OPENVPN_PASSWORD=password
      - OPENVPN_CONFIG=AUTO
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RPC_PASSWORD=
      - TRANSMISSION_RPC_USERNAME=
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=0
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=false
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=999
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=false
      - TRANSMISSION_MAX_PEERS_GLOBAL=999
      - TRANSMISSION_PEER_LIMIT_GLOBAL=999
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=999      
      - TRANSMISSION_SEED_QUEUE_ENABLED=false     
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false      
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=1
      - TRANSMISSION_START_ADDED_TORRENTS=true
      - TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=false

# Transmission with VPN – Bittorrent Downloader
  transmission-vpn-sonarr:
    image: haugene/transmission-openvpn
    container_name: transmission-vpn-sonarr
    hostname: transmission-vpn-sonarr
    restart: always    
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 9092:9091
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /volume1/docker/transmission-vpn-sonarr:/data
      - /volume1/docker/shared:/shared
      - /volume1/Downloads:/data/watch
      - /volume1/Downloads/completed:/data/completed
      - /volume1/Downloads/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=username
      - OPENVPN_PASSWORD=password
      - OPENVPN_CONFIG=AUTO
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RPC_PASSWORD=
      - TRANSMISSION_RPC_USERNAME=
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=0
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=false
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=999
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=false
      - TRANSMISSION_MAX_PEERS_GLOBAL=999
      - TRANSMISSION_PEER_LIMIT_GLOBAL=999
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=999      
      - TRANSMISSION_SEED_QUEUE_ENABLED=false     
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false      
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=1
      - TRANSMISSION_START_ADDED_TORRENTS=true
      - TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=false

########## Music ###################################   

  beets:
    container_name: beets  
    image: linuxserver/beets
    restart: always
    ports:
      - 8337:8337
    environment:
      - PUID=1030
      - PGID=101
      - TZ=America/New_York
    volumes:
      - /volume1/docker/beets:/config
      - /volume1/Media/Music/Normal:/music
      - /volume1/Downloads:/downloads 
      - /volume1/docker/shared:/shared     

  headphones:
    container_name: headphones  
    image: linuxserver/headphones
    restart: always
    ports:
      - 8183:8181
    environment:
      - PUID=1030
      - PGID=101
      - TZ=America/New_York
    volumes:
      - /volume1/docker/headphones:/config
      - /volume1/Media/Music/Normal:/music
      - /volume1/Downloads:/downloads 
      - /volume1/docker/shared:/shared 

  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr
    restart: always
    ports:
      - 8686:8686/tcp
    environment:
      - PUID=1030
      - PGID=101
      - TZ=America\New_York
    volumes:
      - /volume1/docker/lidarr:/config
      - /volume1/Downloads:/downloads
      - /volume1/Media/Music/Normal:/music
      - /volume1/docker/shared:/shared

######### PERSONAL VIDEO RECORDERS ##################

# Radarr – Movie Download and Management
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    hostname: radarr
    volumes:
      - /volume1/docker/radarr:/config
      - /volume1/Downloads/completed:/downloads
      - /volume1/Downloads/completed:/data/completed
      - /volume1/Media/Movies:/movies
      - /volume1/docker/shared:/shared
    ports:
      - 7878:7878
    restart: always
    environment:
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"

# Sonarr – TV Show Download and Management
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    hostname: sonarr
    restart: always
    volumes:
      - /volume1/docker/sonarr:/config
      - /volume1/Downloads/completed:/downloads
      - /volume1/Downloads/completed:/data/completed
      - /volume1/Media/TV Shows:/tv
      - /volume1/docker/shared:/shared
    ports:
      - 8989:8989
    environment:
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"

######### Books ##########
# lazylibrarian – TV Show Download and Management
  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    restart: always
    volumes:
      - /volume1/docker/lazylibrarian:/config
      - /volume1/Downloads/lazylibrarian:/downloads
      - /volume1/Media/Books/Calibre:/books
      - /volume1/docker/shared:/shared
    ports:
      - 5299:5299
    environment:
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"
      - DOCKER_MODS=linuxserver/calibre-web:calibre


######### MEDIA SERVER APPS ##########

# Plex Media Server
  plex:
    image: plexinc/pms-docker  
    container_name: plex
    hostname: plex
    restart: always
    volumes:
      - /volume1/docker/Plex:/config
      - /volume1/docker/Plex/Transcode:/transcode
      - /volume1/Media:/media
      - /volume1/docker/shared:/shared
    network_mode: host
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ="America/New_York"
      - HOSTNAME="Docker Plex"
      - PLEX_CLAIM="plexclaimkey"
      - PLEX_UID=1030
      - PLEX_GID=101
      - ALLOWED_NETWORKS=192.168.1.0/255.255.254.0
      - ADVERTISE_IP=http://192.168.1.208:32400

# Tautulli (aka PlexPy) – Monitoring Plex Usage
  tautulli-deathstar:
    image: linuxserver/tautulli
    container_name: tautulli-deathstar
    hostname: tautulli-deathstar
    restart: always
    volumes:
      - /volume1/docker/tautulli/deathstar/config:/config
      - /volume1/docker/tautulli/deathstar/logs:/logs:ro
      - /volume1/docker/shared:/shared
    ports:
      - 8181:8181
    environment:
      - PUID=1030
      - PGID=101
      - TZ=America/New_York

# Tautulli (aka PlexPy) – Monitoring Plex Usage
  tautulli-synology:
    image: linuxserver/tautulli
    container_name: tautulli-synology
    hostname: tautulli-synology
    restart: always
    volumes:
      - /volume1/docker/tautulli/synology/config:/config
      - /volume1/docker/tautulli/synology/logs:/logs:ro
      - /volume1/docker/shared:/shared
    ports:
      - 8182:8181
    environment:
      - PUID=1030
      - PGID=101
      - TZ=America/New_York    

# Ombi – Accept Requests for your Media Server
  ombi:
    image: linuxserver/ombi 
    container_name: ombi
    hostname: ombi
    restart: always
    volumes:
      - /volume1/docker/ombi:/config
      - /volume1/docker/shared:/shared
    ports:
      - 3579:3579
    environment:
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"

######### SEARCHERS ##########

# Jackett – Torrent Proxy
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    hostname: jackett
    restart: always
    volumes:
      - /volume1/docker/jackett:/config
      - /volume1/Downloads/completed:/downloads
      - /volume1/docker/shared:/shared
    ports:
      - 9117:9117
    environment:
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"

######### Website ##########

# mysql - db for wordpress
  mysql:
    image: mariadb
    container_name: mysql
    hostname: mysql
    restart: always
    volumes:
      - /volume1/docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"

# mysql - db for wordpress2
  mysql2:
    image: mariadb
    container_name: mysql2
    hostname: mysql2
    restart: always
    volumes:
      - /volume1/docker/mysql2:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"      
    
# Wordpress - website 1   
  wordpress:
    image: wordpress
    container_name: wordpress
    hostname: wordpress
    restart: always
    ports:
      - 89:80
    volumes:
      - /volume1/docker/wordpress:/var/www/html
    environment:
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"    
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD=password
    links:
      - mysql
    
# Wordpress - website 2    
  wordpress2:
    image: wordpress
    container_name: wordpress2
    hostname: wordpress2
    restart: always
    ports:
      - 90:80
    volumes:
      - /volume1/docker/wordpress2:/var/www/html
    environment:
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"    
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD=password
    links:
      - mysql2

# Ghost - Proffesional blog
  ghost:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    volumes:
      - /volume1/docker/ghost/blog:/var/lib/ghost/content
    environment:
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"  
      - url=http://192.168.1.208:2368      

########### Network ##########
# Unifi - Centralized network management
  unifi:
    image: jacobalberty/unifi
    container_name: unifi
    hostname: unifi
    restart: always
    volumes:
      - /volume1/docker/unifi:/var/lib/unifi
    network_mode: host
    ports:
      - 3478:3478/udp
      - 8080:8080/tcp
      - 8081:8081/tcp
      - 8443:8443/tcp
      - 8843:8843/tcp
      - 8880:8880/tcp
      - 8883:8883/tcp
    environment:
      - PUID=1030
      - PGID=101
      - TZ="America/New_York" 
    
############ Graphs ##############
 # Influxdb - DB for storing log info
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    command: -config /etc/influxdb/influxdb.conf
    volumes:
      - /volume1/docker/influxdb:/var/lib/influxdb
      - /volume1/docker/influxdb/config:/etc/influxdb/influxdb.conf:ro

# grafana - frontend for graphs
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - /volume1/docker/grafana:/var/lib/grafana
      - /volume1/docker/grafana/config:/etc/grafana/    

# varken -plex/radarr/sonarr graphs
  varken:
    image: boerderij/varken
    container_name: varken
    volumes:
      - /volume1/docker/varken:/config
    environment:
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"        
